### ISSUE TITLE
How would you go about hooking mysql into this set-up? 

### ISSUE THREAD

**Issue by EwanValentine** [denderello/symfony-docker-example#3]
I've got this set-up working, I just wondered how you'd extend it to include mysql? Or if you knew of an example somewhere else?

Current config:

```

api:
  build: images/api
  links:
    - redis
    - db
  volumes:
    - ./images/api/codebase/:/var/www

nginx:
    build: images/nginx
    ports:
        - 8080:80
    links:
        - fpm
        - db
    volumes_from:
        - api
    environment:
        <APP_SERVER_NAME>: development

fpm:
    build: images/php
    links:
        - redis
        - db
    volumes_from:
        - api
    environment:
        APP_SERVER_NAME: development

redis:
    image: redis:2.8.13

db:
    image: drakedroid/mysql-with-data
    expose:
        - "3306"
    ports:
        - "3306:3306"
    environment:
        MYSQL_DATABASE: api_master
        MYSQL_USER: root
        MYSQL_PASSWORD: [REDACTED]
        MYSQL_ROOT_PASSWORD: [REDACTED]


```

I get:

```

[PDOException]
  SQLSTATE[HY000] [2005] Unknown MySQL server host 'db' (2)

```

When I try to run ```docker-compose run api 'php app/console doctrine:schema:generate --force``` 

Thanks in advance!
